version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:base
    ports:
      - 80:80
    depends_on:
      - api

  api:
    image: alexrazek/todolist_alex:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
#      migrations:
#        condition: service_completed_successfully
    volumes:
      - ./.env:/app/.env

  migrations:
    image: alexrazek/todolist_alex:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    command: python3 manage.py migrate

  postgres:
    image: postgres:13.7-alpine   #postgres:latest
#    env_file:
#      - .env
#    environment:
#      POSTGRES_PASSWORD: $DB_PASSWORD
#      POSTGRES_DB: $DB_NAME
#      POSTGRES_USER: $DB_USER
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: