version: "3.9"

services:

  frontend:
    image: sermalenk/skypro-front:lesson_38
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - frontend_nw

  bot:
    image: alexrazek/todolist_alex:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - ./.env
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: >
      sh -c "python3 manage.py runbot"
    networks:
      - backend_nw
      - frontend_nw

  api:
    image: alexrazek/todolist_alex:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: curl -sS http://127.0.0.1:8000/health/ || exit 1
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - backend_nw
      - frontend_nw

  postgres:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_nw

volumes:
  postgres-data:

networks:
  backend_nw:
    driver: bridge
  frontend_nw:
    driver: bridge




