# Generated by Django 4.0.5 on 2022-07-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tguser_verification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'TG User', 'verbose_name_plural': 'TG User'},
        ),
    ]
